name:                sampletex
version:             0.1.0.0
github:              "roridev/sampletex"
license:             BSD3
author:              "roridev"
maintainer:          "prates.aliceic@gmail.com"
copyright:           "2021 roridev"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/roridev/sampletex#readme>

dependencies:
- base >= 4.7 && < 5
- filepath
- directory


library:
  source-dirs: src
  dependencies:
    - megaparsec
    - text
    - lens
    - transformers
    - containers


executables:
  samplec:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sampletex

tests:
  sampletex-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sampletex
